language: c
compiler: gcc

sudo: false

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"

branches:
  only:
    - master

git:
  depth: 3

notifications:
  email: false

before_install:
  - pip install --user hererocks
  - hererocks env --$LUA -rlatest
  - source env/bin/activate

install:
  - luarocks make CFLAGS="-Wall -O2 -fPIC"

script:
  - env/bin/lua test.lua

